### ISSUE TITLE
Ensure that return values are preserved in MS Windows

### ISSUE THREAD

**Issue by whart222** [PyUtilib/pyutilib#22]
The subprocess.run command does not currently provide appropriate return values.

**Comment by ghackebeil** [comment]
What do you mean? We've been using this for quite some time and it seems to work fine.

I'm confused by the commit referenced above as well. The Appveyor tests have been fixed in that failed tests are now reflected in the return code. What was the above commit fixing?

**Comment by whart222** [comment]
Gabe:

I didn't realize that your commits fixed the return code.  But in any case
the output is being masked on MS Windows.  So there's still an issue that
needs to be resolved.

--Bill

**Comment by ghackebeil** [comment]
Agreed. Maybe we should rename this ticket to reflect that. The problem is with output redirection, not the return code.
